-- MySQL Script generated by MySQL Workbench
-- sex 23 ago 2019 21:49:00 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gestor_de_arquivos_BD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestor_de_arquivos_BD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestor_de_arquivos_BD` DEFAULT CHARACTER SET utf8 ;
USE `gestor_de_arquivos_BD` ;

-- -----------------------------------------------------
-- Table `gestor_de_arquivos_BD`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestor_de_arquivos_BD`.`Aluno` (
  `alunoId` INT NOT NULL AUTO_INCREMENT,
  `alunoNome` VARCHAR(45) NOT NULL,
  `alunoEmail` VARCHAR(45) NOT NULL,
  `alunoSenha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`alunoId`),
  UNIQUE INDEX `alunoEmail_UNIQUE` (`alunoEmail` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_de_arquivos_BD`.`Codigo_cadastro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestor_de_arquivos_BD`.`Codigo_cadastro` (
  `codigo` CHAR(6) NOT NULL,
  `codigo_usado` ENUM('0', '1') NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_de_arquivos_BD`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestor_de_arquivos_BD`.`Professor` (
  `profId` INT NOT NULL AUTO_INCREMENT,
  `profNome` VARCHAR(45) NOT NULL,
  `profEmail` VARCHAR(100) NOT NULL,
  `profSenha` VARCHAR(45) NOT NULL,
  `profDisciplina` VARCHAR(45) NOT NULL,
  `profBiografia` VARCHAR(45) NOT NULL,
  `profFoto` LONGBLOB NULL,
  `Codigo_cadastro_codigo` CHAR(6) NOT NULL,
  PRIMARY KEY (`profId`),
  UNIQUE INDEX `profEmail_UNIQUE` (`profEmail` ASC),
  INDEX `fk_Professor_Codigo_cadastro1_idx` (`Codigo_cadastro_codigo` ASC),
  CONSTRAINT `fk_Professor_Codigo_cadastro1`
    FOREIGN KEY (`Codigo_cadastro_codigo`)
    REFERENCES `gestor_de_arquivos_BD`.`Codigo_cadastro` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor_de_arquivos_BD`.`Arquivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestor_de_arquivos_BD`.`Arquivo` (
  `arquivoId` INT NOT NULL,
  `arquivo` LONGBLOB NOT NULL,
  `arquivo_dataUpload` DATE NOT NULL,
  `Professor_profId` INT NOT NULL,
  PRIMARY KEY (`arquivoId`),
  INDEX `fk_Arquivo_Professor_idx` (`Professor_profId` ASC),
  CONSTRAINT `fk_Arquivo_Professor`
    FOREIGN KEY (`Professor_profId`)
    REFERENCES `gestor_de_arquivos_BD`.`Professor` (`profId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
